### ISSUE TITLE
Minor UI: border-bottom

### ISSUE THREAD

**Issue by mdyring** [e-money/lunie-light#102]
Newly introduced border-bottom should not be there for last row ("orders", "pairs", "your stake" and "all validators" tables):
![image](https://user-images.githubusercontent.com/18033781/103413804-55f34900-4b7b-11eb-8d84-eb7e647e4fe2.png)

Seems like like bottom-border is thicker in columns before yield:
![image](https://user-images.githubusercontent.com/18033781/103413783-3b20d480-4b7b-11eb-80df-60762df21526.png)

![image](https://user-images.githubusercontent.com/18033781/103413819-6a374600-4b7b-11eb-9658-3f206eacab41.png)

**Comment by Bitcoinera** [comment]
I think that is in fact the shadow-box attribute?

**Comment by Bitcoinera** [comment]
`box-shadow`, yes, that is what is to be seen there

![image](https://user-images.githubusercontent.com/40721795/103420988-564f0c80-4b9a-11eb-88aa-c4ccff08e517.png)

We can close this one
