### ISSUE TITLE
Make unstake table identical to stake

### ISSUE THREAD

**Issue by mdyring** [e-money/lunie-light#107]
Would be good to have a "Stake" column in the Unstake table, as well as populate the shift the header columns so they match with the table data: 

Can be reproduced with: emoney1dhdlcrqdk0ze9n22my5e0ttyayc2zxgv42vmzq

![image](https://user-images.githubusercontent.com/18033781/103463780-5af8f980-4d2f-11eb-9c4e-0918dda7883f.png)

**Comment by Bitcoinera** [comment]
Well, they cannot be identical since the End Time property doesn't exist in Delegations and this should be reflected

**Comment by mdyring** [comment]
Sorry, I was unclear. I did not intend them for them to be 100% identical, but just to 
1) create a "Stake" column (and move the amount below the Validator Name into that column)
2) Fix the column headers by shifting them left.
