### ISSUE TITLE
Rewards for other tokens are always zero?

### ISSUE THREAD

**Issue by Bitcoinera** [e-money/lunie-light#14]
Is it possible to get rewards in alt-denoms in e-Money? Otherwise we should remove them from the Claim Modal

![image](https://user-images.githubusercontent.com/40721795/100631614-31ae0d80-332c-11eb-9931-6fb815ed1877.png)

**Comment by mdyring** [comment]
Yeah, rewards can be in other denoms as well, as fees can be paid on other tokens than NGM.

**Comment by Bitcoinera** [comment]
OK, thank you. Closing this then
