### ISSUE TITLE
Use token/fiat exchange rates in wallet

### ISSUE THREAD

**Issue by mdyring** [e-money/lunie-light#16]
See https://github.com/e-money/em-ledger/blob/master/docs/tokens.md for token/rate specs.

- [ ] Add general support for [displaying](https://github.com/e-money/em-ledger/blob/master/docs/tokens.md#displaying-amounts) lunieCoins fiat values using the rate/token information. Might make sense to remove the stablecoins from network.js and then add them dynamically? 
- [ ] Display fiat amounts in portfolio balances
- [ ] Display fiat amounts in transactions page
- [ ] Let user input (and display) fiat amounts in the send modal forms
- [ ] When implemented, swap should also use fiat input/display

**Comment by Bitcoinera** [comment]
Ah, fiat values. Yes, we need to bring that one also back :+1:
