### ISSUE TITLE
Fee entry field is not being applied

### ISSUE THREAD

**Issue by haasted** [e-money/lunie-light#18]
Specifying a custom fee does not seem to have any impact on the transaction being sent to the Ledger device.
![Screenshot 2020-12-01 at 13 04 55](https://user-images.githubusercontent.com/1016810/100738866-8ad27b80-33d6-11eb-80e2-189ad051fdc9.png)
![2020-12-01 13 05 26-1](https://user-images.githubusercontent.com/1016810/100738954-b0f81b80-33d6-11eb-8b0d-0c5855e674f0.jpg)

**Comment by Bitcoinera** [comment]
I just tried and cannot reproduced. On the screenshot you are actually selecting NGM, aren't you?

**Comment by haasted** [comment]
@Bitcoinera : Yes, I selected NGM as a fee denomination. The issue is that the 0.8 NGM specified in the fee-modal is not applied. The generated transaction contains a fee of 0.2 NGM instead, which I believe is the default value.

**Comment by mdyring** [comment]
Related to #16 - I don't think users should be allowed to manually tweak fee settings, as the have centralised gas prices

**Comment by Bitcoinera** [comment]
> The issue is that the 0.8 NGM specified in the fee-modal is not applied. The generated transaction contains a fee of 0.2 NGM instead, which I believe is the default value.

ah ok, I understand. The problem is that the fee amount is not consistent. OK, checking

**Comment by Bitcoinera** [comment]
But yes, the solution would be first disabling the input field so users cannot select the fee amount anymore
