### ISSUE TITLE
Use +/- signs to reflect change in account balances

### ISSUE THREAD

**Issue by mdyring** [e-money/lunie-light#19]
To align with the +/- convention for display of amounts for market orders (#17), please

1) Add - for sent amounts 
2) Add + for received amounts
3) Add + for withdraw rewards
4) Add - for staked amounts
5) Add + for unstaked amounts

I guess the nicest way to do it is, is when setting the amounts inside the respective reducers and then force a sign when formatting for display.

**Comment by Bitcoinera** [comment]
OK, you mean in PageTransactions, as I understand. Yes, it is a good idea. We could also use colors (green for additionss, red for subtractions)

**Comment by mdyring** [comment]
> OK, you mean in PageTransactions, as I understand. Yes, it is a good idea. We could also use colors (green for additionss, red for subtractions)

Yep, correct PageTransactions. 👍 

I prefer to have +/- indications as red/green has different meaning across cultures and might get lost when copy/pasting, on printout etc.

**Comment by Bitcoinera** [comment]
> I prefer to have +/- indications as red/green has different meaning across cultures and might get lost when copy/pasting, on black/white printouts etc.

Sorry, I meant we can have both. It is more visual like that

![image](https://user-images.githubusercontent.com/40721795/100776504-eb78ad00-3404-11eb-946a-e0b5c2c54a63.png)

**Comment by Bitcoinera** [comment]
OK, only missing checking if it is a filled order, but the sign logic is there, also for the other transactions:

![image](https://user-images.githubusercontent.com/40721795/100776734-309cdf00-3405-11eb-8fd3-6b774340f23c.png)
