### ISSUE TITLE
Unifying right side content alignment

### ISSUE THREAD

**Issue by mdyring** [e-money/lunie-light#36]
Scrolling through the different menu items, the alignment of the right hand display varies quiet a bit. Ideally they should match:

![image](https://user-images.githubusercontent.com/18033781/101628117-a285b180-3a1f-11eb-908c-91c7a94075fd.png)
![image](https://user-images.githubusercontent.com/18033781/101628044-86821000-3a1f-11eb-91d7-fe17ce978a17.png)
![image](https://user-images.githubusercontent.com/18033781/101628142-a87b9280-3a1f-11eb-8ccb-4e9cc37287ad.png)
![image](https://user-images.githubusercontent.com/18033781/101628153-aca7b000-3a1f-11eb-9cd5-e175b8977cf4.png)

**Comment by Bitcoinera** [comment]
Ah, I see what you mean. Yes, it should actually match
