### ISSUE TITLE
Minor improvement to active instruments

### ISSUE THREAD

**Issue by mdyring** [e-money/lunie-light#37]
Column name "Pair" should be "Instrument" and to make it clear that it is directional, maybe we can use "src → dst" naming instead of "src/dst"?

![image](https://user-images.githubusercontent.com/18033781/101644431-7412d100-3a35-11eb-941f-fb81f6a73407.png)

**Comment by Bitcoinera** [comment]
Mmm, I think we need to name things as it is more intuitive and easy to understand. All exchanges call that a pair and I think the real logic behind is not relevant for the average user. I think it is better to leave it the way it is

**Comment by mdyring** [comment]
For me it is mainly about consistency, so that we write "Active Instruments" but then introduce the term "Pair".. So we should either use "Pairs" or "Instruments", but not both to avoid confusing users. Having to pick between the two, I believe "Instruments" is the better choice.

**Comment by Bitcoinera** [comment]
> For me it is mainly about consistency: We write "Active Instruments" but then introduce the term "Pair" in the table. Having to pick between the two, I believe "Instruments" is the better choice.

I think "pair" in the contrary is a better choice, since "instrument" the average user won't know what it means. I have actually never seen this term anywhere else, to be honest :shrug:  In all exchanges I see "pair".

You are right saying "Active Instruments" is confusing. It should say "Market Pairs" or "Latest Trades" or "Active Pairs". That I agree with

**Comment by mdyring** [comment]
Yes agreed. So what about "Market Information" instead of "All Instruments" and then we keep the "Pair" name for the column?

**Comment by Bitcoinera** [comment]
> So what about "Market Information"

I :heart:  "Market Information"
