### ISSUE TITLE
Change default validator ordering

### ISSUE THREAD

**Issue by mdyring** [e-money/lunie-light#4]
Sort by <voting power ASC, fees DESC> to make lower VP validators more visible.

**Comment by Bitcoinera** [comment]
When you say `<voting power ASC, fees DESC>` you mean you would like a combined way to order validators, Martin? Combining Voting Power and Rewards? That would be more complicated, crossing values from two different columns.

The solution I propose: a dictionary Property -> Order. (So according to property, there is a default order)
