### ISSUE TITLE
Stake: Support redelegation

### ISSUE THREAD

**Issue by mdyring** [e-money/lunie-light#49]
Could be a "Restake" button here in the validator view?

![image](https://user-images.githubusercontent.com/18033781/101779308-645ac180-3af5-11eb-8949-2a5361cfebda.png)

**Comment by Bitcoinera** [comment]
This would be actually quite easy to do actually, since the code is already kind of there in old Lunie

**Comment by Bitcoinera** [comment]
What do you think about this idea:

We have a "Restake" button on the PageValidator of the validator we are currently delegating to. Then on the modal there is a "From" fields that is actually disabled that is this validator, and we can choose the "To"

Another option is to do it like we had in Lunie: 
Every stake modal has the "From" and the "To" field, and the "From" is by default the user address.

Another thing to think about is the validator selection component. In Lunie we had it like a dropdown list

**Comment by Bitcoinera** [comment]
OK, I went in the end for the last option and with the dropdown list to select either the user address or a validator to stake from.

I think it is kind of intuitive. Feedback welcome!
