### ISSUE TITLE
Swap: Add "Best Price" and show more instruments

### ISSUE THREAD

**Issue by mdyring** [e-money/lunie-light#63]
Instruments query now return more data (best price) and also available instruments.

https://emoney.validator.network/api/market/instruments

I don't see them in the market information though, could this be because it filters those that have no last_traded @Bitcoinera ?

I think it would be great to show instruments that have either a last_price or best_price 👍

**Comment by Bitcoinera** [comment]
> could this be because it filters those that have no last_traded @Bitcoinera ?

Yes, exactly, I was filtering those out since they didn't include any other information. But now this has changed

> I think it would be great to show instruments that have either a last_price or best_price

:ok_hand:
