### ISSUE TITLE
Market Information requires being signed in

### ISSUE THREAD

**Issue by mdyring** [e-money/lunie-light#67]
Before signing in:
![image](https://user-images.githubusercontent.com/18033781/102198692-f92d3880-3ec2-11eb-8a63-89280453327a.png)

After signing in:
![image](https://user-images.githubusercontent.com/18033781/102198763-13671680-3ec3-11eb-803a-c7bfe65f75dd.png)

**Comment by Bitcoinera** [comment]
Mmm, good catch. It shouldn't be that way
