### ISSUE TITLE
Add "Trade" button at end of each market information line

### ISSUE THREAD

**Issue by mdyring** [e-money/lunie-light#70]
I think that would be a nice addition, similar layout as "Cancel" button but with a maybe this icon?
https://material.io/resources/icons/?icon=close_fullscreen&style=baseline

Create Order modal would then have the source/dest denoms preselected based on the market pair.

We can remove "Create Order" button then.

I am worried it will look messy though? Maybe we can give it a try.

**Comment by mdyring** [comment]
Or maybe this icon instead: https://material.io/resources/icons/?icon=swap_horiz&style=baseline

**Comment by Bitcoinera** [comment]
Where do you mean we should place this "Trade" button? In the Active Instruments rows?

![image](https://user-images.githubusercontent.com/40721795/102656850-e04bae00-4174-11eb-9052-c7666285218a.png)

**Comment by mdyring** [comment]
> Where do you mean we should place this "Trade" button? In the Active Instruments rows?
> 
> ![image](https://user-images.githubusercontent.com/40721795/102656850-e04bae00-4174-11eb-9052-c7666285218a.png)

Yeah, one icon for each row similar to the Portfolio page. The source/dest denoms can then be pre-populated and the "Create Order" button removed.

TBH I am not sure this will work better than what is already there.. But could be worth a shot just to see.
