### ISSUE TITLE
Sending multiple coins fail

### ISSUE THREAD

**Issue by mdyring** [e-money/lunie-light#76]
![image](https://user-images.githubusercontent.com/18033781/102655317-69151a80-4172-11eb-97dc-4182e44e69f8.png)
Transaction data from Keplr:
```
{
  "account_number": "275",
  "chain_id": "emoney-2",
  "fee": {
    "amount": [
      {
        "amount": "100000",
        "denom": "ungm"
      }
    ],
    "gas": "100000"
  },
  "memo": "",
  "msgs": [
    {
      "type": "cosmos-sdk/MsgSend",
      "value": {
        "amount": [
          {
            "amount": "1000000",
            "denom": "enok"
          },
          {
            "amount": "2000000",
            "denom": "edkk"
          }
        ],
        "from_address": "emoney1dhdlcrqdk0ze9n22my5e0ttyayc2zxgv42vmzq",
        "to_address": "emoney1dhdlcrqdk0ze9n22my5e0ttyayc2zxgv42vmzq"
      }
    }
  ],
  "sequence": "13"
}
```

**Comment by Bitcoinera** [comment]
I remember this bug, was also present in the original repo. But at first sight might be just renaming `amount` to `amounts`? Let me try that

**Comment by Bitcoinera** [comment]
I am still wondering what is causing this exactly. Once I got it working, just leaving the execution paused longer.

It is very strange

![image](https://user-images.githubusercontent.com/40721795/102691760-25bcb980-420f-11eb-93e6-a5346e8387eb.png)

**Comment by mdyring** [comment]
Yeah, also working here with Ledger device now.. Hm.

One thing I did notice is that these tx's may run out of gas (default is 80k). Could make sense to multiply the gas amount with number of denoms sent.. So 2 denoms == 160k gas.

See https://e-money.net/transactions/83D5B485A3953E16E3DDFDBD73862587930F97D75D9DD109E40EB290616D911F

**Comment by Bitcoinera** [comment]
Maybe, like you said, it is simply a lack of gas problem, giving the wrong error

**Comment by mdyring** [comment]
Unable to reproduce. Closing for now.
