### ISSUE TITLE
Display of staking amount/rewards differ

### ISSUE THREAD

**Issue by mdyring** [e-money/lunie-light#80]
![image](https://user-images.githubusercontent.com/18033781/102719353-dd27fd80-42ed-11eb-9190-d62a211c2824.png)

After clicking validator:

![image](https://user-images.githubusercontent.com/18033781/102719361-eb761980-42ed-11eb-85ae-ad77ba2a2117.png)

**Comment by Bitcoinera** [comment]
Ah yes, I had seen this one before. Thanks for opening an issue about this
