### ISSUE TITLE
Transactions: Move Memo to the left 

### ISSUE THREAD

**Issue by mdyring** [e-money/lunie-light#98]
Account emoney1n6kqrlmdhenstppxuaemczplnex0cyk9ddm3yd can be used for reproducing.

Would be great to have the memo on the left hand side and leave the fee on the right side (as it is today for txs without memo)

![image](https://user-images.githubusercontent.com/18033781/103407170-d6a34c80-4b5d-11eb-8d3b-d3de57b8c34b.png)

**Comment by Bitcoinera** [comment]
Oops, didn't see that one. Easy one :+1:
